image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      python3.10 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      source .venv/bin/activate
      streamlit run app.py --server.port 8080 --server.address 0.0.0.0
ports:
  - port: 8080
    onOpen: open-browser